CREATE TABLE IF NOT EXISTS USERS (
    USERID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    LOGINPASSWORD VARCHAR(255) NOT NULL,
    USERROLE VARCHAR(50) NOT NULL DEFAULT 'STUDENT',
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FULLNAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USERNAME),
    CONSTRAINT CHKROLE CHECK (USERROLE IN ('ROLE_TEACHER', 'ROLE_STUDENT'))
);
CREATE TABLE IF NOT EXISTS LECTURE (
    LECTUREID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    LECTURENAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (LECTUREID)
);
CREATE TABLE IF NOT EXISTS LECTURE_NOTE (
    NOTEID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    NOTE_NAME VARCHAR(255) NOT NULL,
    LECTUREID BIGINT NOT NULL,
    FOREIGN KEY (LECTUREID) REFERENCES LECTURE(LECTUREID),
    PRIMARY KEY (NOTEID)
);
CREATE TABLE IF NOT EXISTS ATTACHMENT (
    ATTACHMENTID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    NOTEID BIGINT NOT NULL,
    FOREIGN KEY (NOTEID) REFERENCES LECTURE_NOTE(NOTEID),
    PRIMARY KEY (ATTACHMENTID)
);
CREATE TABLE IF NOT EXISTS LECTURE_COMMENT (
    LCID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    COMMENT VARCHAR(255) NOT NULL,
    USERID BIGINT NOT NULL,
    LECTUREID BIGINT NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    COMMENTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LECTUREID) REFERENCES LECTURE(LECTUREID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    PRIMARY KEY (LCID)
);
CREATE TABLE IF NOT EXISTS POLL (
    POLLID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    POLLNAME VARCHAR(255) NOT NULL,
    POLLANSWER TEXT NOT NULL,
    PRIMARY KEY (POLLID)
);
CREATE TABLE IF NOT EXISTS POLL_COMMENT (
    PCID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    COMMENT VARCHAR(255) NOT NULL,
    USERID BIGINT NOT NULL,
    POLLID BIGINT NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    COMMENTTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POLLID) REFERENCES POLL(POLLID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    PRIMARY KEY (PCID)
);

CREATE TABLE IF NOT EXISTS POLL_ANSWER (
    ANSWERID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
    ANSWER VARCHAR(255) NOT NULL,
    USERID BIGINT NOT NULL,
    POLLID BIGINT NOT NULL,
    FOREIGN KEY (POLLID) REFERENCES POLL(POLLID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    PRIMARY KEY (ANSWERID)
);